services:
  api:
    build: api/
    entrypoint: uvicorn main:app --host 0.0.0.0 --port 8080 --reload
    volumes:
      - ./api/src:/workspace/src
    # don't start if overfast api hasn't started yet
    depends_on:
      postgres:
        condition: service_started
    ports:
      - 81:8080
    # checking service is up every 5 seconds
    healthcheck:
      test: ["CMD-SHELL", "curl http://0.0.0.0:8080/health || exit 1"]
      interval: 60s
      timeout: 5s
    env_file:
      - ./api/.env
    # scrape every week
    # healthcheck:
    #   test: ["CMD-SHELL", "curl http://0.0.0.0:8080/scrape || exit 1"]
    #   interval: 10080s # 1 week
    #   timeout: 60s
    
  postgres:
    build: infra/postgres
    ports:
      - 5432:5432
    env_file:
      - ./infra/postgres/.env