include:
  - path: infra/airflow/docker-compose.yaml
    ports:
      - 8080:8080
    env_file:
      - .env.global
      - infra/airflow/.env
      
services:
  api:
    build: api/
    entrypoint: uvicorn main:app --host 0.0.0.0 --port 8080 --reload
    volumes:
      - ./api/src:/workspace/src
    # don't start if overfast api hasn't started yet
    depends_on:
      mongodb:
        condition: service_started
      postgres:
        condition: service_started
    ports:
      - 81:8080
    env_file:
      - .env.global
      - ./api/.env
    networks:
      - lol_api_network
    # checking service is up every 5 seconds
    healthcheck:
      test: ["CMD-SHELL", "curl http://0.0.0.0:8080/health || exit 1"]
      interval: 60s
      timeout: 5s
    # scrape every week
    # healthcheck:
    #   test: ["CMD-SHELL", "curl http://0.0.0.0:8080/scrape || exit 1"]
    #   interval: 10080s # 1 week
    #   timeout: 60s
    
  mongodb:
    build: infra/mongodb
    ports:
      - "27017:27017"
    env_file:
      - .env.global
    networks:
      - lol_api_network
    volumes: 
      - mongodb_data:/data/db

  postgres:
    build: infra/postgres
    ports:
      - 5432:5432
    env_file:
      - .env.global
      - ./infra/postgres/.env
    networks:
      - lol_api_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 
    driver: local
    driver_opts:
      o: bind
      type: none
      device: infra/data/postgres
  mongodb_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: infra/data/mongodb

networks:
  lol_api_network:
    driver: bridge