services:
  api:
    build: api/
    entrypoint: uvicorn main:app --host 0.0.0.0 --port 8080 --reload
    volumes:
      - ./api/src:/workspace/src
    # don't start if overfast api hasn't started yet
    depends_on:
      mongodb:
        condition: service_started
    ports:
      - 81:8080
    networks:
      - lol_api_network

    # checking service is up every 5 seconds
   
    #env_file:
      #- ./api/.env
    # scrape every week
    # healthcheck:
    #   test: ["CMD-SHELL", "curl http://0.0.0.0:8080/scrape || exit 1"]
    #   interval: 10080s # 1 week
    #   timeout: 60s
    
  mongodb:
    build: infra/mongodb
    ports:
      - "27017:27017"
    # volumes:
      # - ./data/db:/data/db
    networks:
      - lol_api_network

networks:
  lol_api_network:
    driver: bridge
